import { Paper } from '@material-ui/core'

import { voters } from './election-parameters'

const redHex = '#e53739'

const VoteToken = ({ s }: { s?: boolean }) => (
  <span style={{ color: redHex, fontWeight: 'bold' }}>Vote Token{s ? 's' : ''}</span>
)
const Highlight = (props: { children: string }) => (
  <span style={{ backgroundColor: `${redHex}44`, border: `1px solid ${redHex}`, padding: '0 2px' }} {...props} />
)

export default function VoterList(): JSX.Element {
  return (
    <>
      <Paper elevation={3} style={{ marginBottom: 30, padding: '0.5rem 1.5rem' }}>
        <p>
          From: <b>elections@sfgov.org</b> <br />
          To: <b>you@email.com</b> <br />
          Subject: <b>Your Ballot for SF Mayor</b>
        </p>
        <p>Voting for our next SF Mayor is now open.</p>
        <p>Votes accepted for the next 14 days.</p>
        <p>
          Click here to securely cast your vote: <br />
          <a style={{ cursor: 'pointer' }}>
            www.sfgov.org/2020election?id=
            <Highlight>{voters[0].token}</Highlight>
          </a>
        </p>
        <p>
          <i style={{ fontSize: 12 }}>
            This link is unique for you. Don&apos;t share it with anyone, or they&apos;ll be able to take your vote. (
            <a style={{ cursor: 'pointer' }}>Help</a>)
          </i>
        </p>
      </Paper>
      <p>
        The point of this step is to get each voter their {<VoteToken />}, highlighted in <Highlight>red</Highlight> in
        the email link.
      </p>
      <p style={{ fontSize: 11 }}>
        For this demo, we present an easy distribution channel — a simple email — but voting authorities could use other
        options, including 2-factor authentication methods.
      </p>
      <div>
        <p style={{ fontWeight: 'bold' }}>Key Properties of {<VoteToken s />}</p>
        <ul style={{ bottom: 10, paddingInlineStart: 15, position: 'relative' }}>
          {[
            'required to vote',
            'unique per voter',
            'generated by voting authority',
            'can only be used once (keep secret until used!)',
            'voting authority can invalidate individual Tokens, & generate new ones, if necessary',
            'the public can see all Vote Tokens generated, invalidated, or used (but not content of any votes)',
          ].map((item, index) => (
            <li key={index} style={{ fontSize: 7, marginBottom: 5 }}>
              <span style={{ fontSize: 14, position: 'relative', top: 2 }}>{item}</span>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}
